'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('grades', [
      {
        grade: 'Turma 1',
        number_students: 19,
        school_id: 1,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 2',
        number_students: 22,
        school_id: 1,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 3',
        number_students: 16,
        school_id: 1,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 4',
        number_students: 31,
        school_id: 1,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 5',
        number_students: 26,
        school_id: 1,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 6',
        number_students: 39,
        school_id: 1,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 1',
        number_students: 19,
        school_id: 2,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 2',
        number_students: 22,
        school_id: 2,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 3',
        number_students: 16,
        school_id: 2,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 4',
        number_students: 31,
        school_id: 2,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 5',
        number_students: 26,
        school_id: 2,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 6',
        number_students: 39,
        school_id: 2,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 1',
        number_students: 19,
        school_id: 3,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 2',
        number_students: 22,
        school_id: 3,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 3',
        number_students: 16,
        school_id: 3,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 4',
        number_students: 31,
        school_id: 3,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 5',
        number_students: 26,
        school_id: 3,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 6',
        number_students: 39,
        school_id: 3,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 1',
        number_students: 19,
        school_id: 4,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 2',
        number_students: 22,
        school_id: 4,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 3',
        number_students: 16,
        school_id: 4,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 4',
        number_students: 31,
        school_id: 4,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 5',
        number_students: 26,
        school_id: 4,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 6',
        number_students: 39,
        school_id: 4,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 1',
        number_students: 19,
        school_id: 5,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 2',
        number_students: 22,
        school_id: 5,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 3',
        number_students: 16,
        school_id: 5,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 4',
        number_students: 31,
        school_id: 5,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 5',
        number_students: 26,
        school_id: 5,
        createdAt: new Date,
        updatedAt: new Date,
      },
      {
        grade: 'Turma 6',
        number_students: 39,
        school_id: 5,
        createdAt: new Date,
        updatedAt: new Date,
      }], {});
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('grades', null, {});
  }
};